version: "3.8"
services:
  fork-snapshot-data:
    build: .
    volumes:
      - ./:/app
    command: "python ohm_fork_data/get_snapshot.py"

  historic-data:
    build: .
    volumes:
      - ./:/app
    command: "python ohm_fork_data/get_data.py"

  stable-farm-data:
    build: .
    volumes:
      - ./:/app
    command: "python stable_farm_data/get_curve_official_pool_snapshot.py"
